//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueTestRun.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrueTestRun.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy thêm user đầu tiên để bắt đầu sử dụng hệ thống..
        /// </summary>
        public static string AddFirstUser {
            get {
                return ResourceManager.GetString("AddFirstUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm User đầu tiên.
        /// </summary>
        public static string AddFirstUserButton {
            get {
                return ResourceManager.GetString("AddFirstUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú bổ sung hoặc yêu cầu chỉnh sửa đặc biệt cho request này..
        /// </summary>
        public static string AdditionalNotes {
            get {
                return ResourceManager.GetString("AdditionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADID đã tồn tại.
        /// </summary>
        public static string ADIDAlreadyExists {
            get {
                return ResourceManager.GetString("ADIDAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADID không tồn tại.
        /// </summary>
        public static string ADIDNotExist {
            get {
                return ResourceManager.GetString("ADIDNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sau Test Run.
        /// </summary>
        public static string AfterTestRun {
            get {
                return ResourceManager.GetString("AfterTestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả các request đều được xử lý thành công hoặc đang trong quá trình xử lý..
        /// </summary>
        public static string AllRequestsSuccessful {
            get {
                return ResourceManager.GetString("AllRequestsSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toàn hệ thống.
        /// </summary>
        public static string AllSystem {
            get {
                return ResourceManager.GetString("AllSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoại quan (外観検査).
        /// </summary>
        public static string AppearanceInspection {
            get {
                return ResourceManager.GetString("AppearanceInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phê duyệt và đóng dấu.
        /// </summary>
        public static string ApprovalAndStamp {
            get {
                return ResourceManager.GetString("ApprovalAndStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phê duyệt Request.
        /// </summary>
        public static string ApprovalForm {
            get {
                return ResourceManager.GetString("ApprovalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú này sẽ được lưu trong lịch sử phê duyệt và hiển thị trên Excel..
        /// </summary>
        public static string ApprovalHistoryNote {
            get {
                return ResourceManager.GetString("ApprovalHistoryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phê duyệt/Xử lý.
        /// </summary>
        public static string ApprovalProcess {
            get {
                return ResourceManager.GetString("ApprovalProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phê duyệt.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người phê duyệt.
        /// </summary>
        public static string ApproverPerson {
            get {
                return ResourceManager.GetString("ApproverPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang phê duyệt.
        /// </summary>
        public static string Approving {
            get {
                return ResourceManager.GetString("Approving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu đính kèm.
        /// </summary>
        public static string AttachedDocuments {
            get {
                return ResourceManager.GetString("AttachedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trước Test Run.
        /// </summary>
        public static string BeforeTestRun {
            get {
                return ResourceManager.GetString("BeforeTestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nhập {0} ký tự..
        /// </summary>
        public static string CharactersEntered {
            get {
                return ResourceManager.GetString("CharactersEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa tick vào checkbox &quot;Đã nhận hàng test run&quot;. Bạn có chắc muốn tiếp tục?.
        /// </summary>
        public static string CheckboxNotChecked {
            get {
                return ResourceManager.GetString("CheckboxNotChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn để xem tài liệu đính kèm.
        /// </summary>
        public static string ClickToViewDocuments {
            get {
                return ResourceManager.GetString("ClickToViewDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành và chuyển tiếp.
        /// </summary>
        public static string CompleteAndForward {
            get {
                return ResourceManager.GetString("CompleteAndForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request đã hoàn thành.
        /// </summary>
        public static string CompletedRequests {
            get {
                return ResourceManager.GetString("CompletedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request đã hoàn thành.
        /// </summary>
        public static string CompletedRequestsTitle {
            get {
                return ResourceManager.GetString("CompletedRequestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ hoàn thành.
        /// </summary>
        public static string CompletionRate {
            get {
                return ResourceManager.GetString("CompletionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Linh Kiện.
        /// </summary>
        public static string ComponentCode {
            get {
                return ResourceManager.GetString("ComponentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Linh Kiện.
        /// </summary>
        public static string ComponentName {
            get {
                return ResourceManager.GetString("ComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn phê duyệt đơn này?.
        /// </summary>
        public static string ConfirmApprove {
            get {
                return ResourceManager.GetString("ConfirmApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng xác nhận (Step 0).
        /// </summary>
        public static string ConfirmationChecklist {
            get {
                return ResourceManager.GetString("ConfirmationChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn hoàn thành và chuyển tiếp đơn này?.
        /// </summary>
        public static string ConfirmComplete {
            get {
                return ResourceManager.GetString("ConfirmComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa user &quot;{0}&quot; ({1})?.
        /// </summary>
        public static string ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("ConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xác nhận FA sample.
        /// </summary>
        public static string ConfirmedFASample {
            get {
                return ResourceManager.GetString("ConfirmedFASample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xác nhận lắp ráp trước.
        /// </summary>
        public static string ConfirmedPreAssembly {
            get {
                return ResourceManager.GetString("ConfirmedPreAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn phê duyệt cuối cùng đơn này?.
        /// </summary>
        public static string ConfirmFinalApproval {
            get {
                return ResourceManager.GetString("ConfirmFinalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận từ chối.
        /// </summary>
        public static string ConfirmReject {
            get {
                return ResourceManager.GetString("ConfirmReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn từ chối đơn này?.
        /// </summary>
        public static string ConfirmRejectRequest {
            get {
                return ResourceManager.GetString("ConfirmRejectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo và Gửi phê duyệt.
        /// </summary>
        public static string CreateAndSubmit {
            get {
                return ResourceManager.GetString("CreateAndSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Request đầu tiên.
        /// </summary>
        public static string CreateFirstRequest {
            get {
                return ResourceManager.GetString("CreateFirstRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Request mới.
        /// </summary>
        public static string CreateNewRequest {
            get {
                return ResourceManager.GetString("CreateNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bước hiện tại.
        /// </summary>
        public static string CurrentStep {
            get {
                return ResourceManager.GetString("CurrentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang điền form.
        /// </summary>
        public static string DataEntry {
            get {
                return ResourceManager.GetString("DataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điền form và ghi nhập thông tin.
        /// </summary>
        public static string DataEntryAndInput {
            get {
                return ResourceManager.GetString("DataEntryAndInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người ghi nhập.
        /// </summary>
        public static string DataEntryPerson {
            get {
                return ResourceManager.GetString("DataEntryPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi xóa tài liệu.
        /// </summary>
        public static string DeleteDocumentError {
            get {
                return ResourceManager.GetString("DeleteDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tài liệu thành công!.
        /// </summary>
        public static string DeleteDocumentSuccess {
            get {
                return ResourceManager.GetString("DeleteDocumentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa user.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả chi tiết vấn đề NG....
        /// </summary>
        public static string DescribeNGDetails {
            get {
                return ResourceManager.GetString("DescribeNGDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng mô tả chi tiết công việc đã thực hiện....
        /// </summary>
        public static string DescribeWorkPlaceholder {
            get {
                return ResourceManager.GetString("DescribeWorkPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phê duyệt chỉ định.
        /// </summary>
        public static string DesignatedApproval {
            get {
                return ResourceManager.GetString("DesignatedApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed by Pham Duc Anh - R&amp;D PE | Brother Vietnam.
        /// </summary>
        public static string DesignedBy {
            get {
                return ResourceManager.GetString("DesignedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng mô tả chi tiết để người phê duyệt tiếp theo hiểu rõ tình hình..
        /// </summary>
        public static string DetailedDescription {
            get {
                return ResourceManager.GetString("DetailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tài liệu.
        /// </summary>
        public static string DocumentList {
            get {
                return ResourceManager.GetString("DocumentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài liệu.
        /// </summary>
        public static string DocumentNotFound {
            get {
                return ResourceManager.GetString("DocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có tài khoản?.
        /// </summary>
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải về.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kéo thả file vào đây hoặc.
        /// </summary>
        public static string DragDropFiles {
            get {
                return ResourceManager.GetString("DragDropFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giữa Test Run.
        /// </summary>
        public static string DuringTestRun {
            get {
                return ResourceManager.GetString("DuringTestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thông tin.
        /// </summary>
        public static string EditInfo {
            get {
                return ResourceManager.GetString("EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa đơn ngay.
        /// </summary>
        public static string EditRequestNow {
            get {
                return ResourceManager.GetString("EditRequestNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập ghi chú cho FA sample....
        /// </summary>
        public static string EnterFASampleNotes {
            get {
                return ResourceManager.GetString("EnterFASampleNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập ghi chú của G.M (tùy chọn)....
        /// </summary>
        public static string EnterGMNotes {
            get {
                return ResourceManager.GetString("EnterGMNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập ghi chú cho kiểm tra....
        /// </summary>
        public static string EnterInspectionNotes {
            get {
                return ResourceManager.GetString("EnterInspectionNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập comment cho KTLM....
        /// </summary>
        public static string EnterKTLMComment {
            get {
                return ResourceManager.GetString("EnterKTLMComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập comment cho KTTB....
        /// </summary>
        public static string EnterKTTBComment {
            get {
                return ResourceManager.GetString("EnterKTTBComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập ghi chú hoặc chỉnh sửa cần thiết....
        /// </summary>
        public static string EnterNotesPlaceholder {
            get {
                return ResourceManager.GetString("EnterNotesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập ghi chú cho lắp ráp trước....
        /// </summary>
        public static string EnterPreAssemblyNotes {
            get {
                return ResourceManager.GetString("EnterPreAssemblyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lý do từ chối (tùy chọn)....
        /// </summary>
        public static string EnterRejectReason {
            get {
                return ResourceManager.GetString("EnterRejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPE-EE kiểm tra.
        /// </summary>
        public static string EPEEEInspection {
            get {
                return ResourceManager.GetString("EPEEEInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi tải file.
        /// </summary>
        public static string ErrorLoadingFile {
            get {
                return ResourceManager.GetString("ErrorLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Excel.
        /// </summary>
        public static string ExcelPreview {
            get {
                return ResourceManager.GetString("ExcelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thực hiện &amp; Kiểm tra.
        /// </summary>
        public static string ExecuteAndInspect {
            get {
                return ResourceManager.GetString("ExecuteAndInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà máy.
        /// </summary>
        public static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên file.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không tồn tại.
        /// </summary>
        public static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File quá lớn. Vui lòng chọn file nhỏ hơn 10MB.
        /// </summary>
        public static string FileTooLargeSpecific {
            get {
                return ResourceManager.GetString("FileTooLargeSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phê duyệt cuối cùng (G.M).
        /// </summary>
        public static string FinalApproval {
            get {
                return ResourceManager.GetString("FinalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú phê duyệt cuối cùng:.
        /// </summary>
        public static string FinalApprovalNotes {
            get {
                return ResourceManager.GetString("FinalApprovalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thiện &amp; Kết thúc.
        /// </summary>
        public static string FinalizeAndComplete {
            get {
                return ResourceManager.GetString("FinalizeAndComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng (機能検査).
        /// </summary>
        public static string FunctionInspection {
            get {
                return ResourceManager.GetString("FunctionInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chung.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào, {0}!.
        /// </summary>
        public static string HelloUser {
            get {
                return ResourceManager.GetString("HelloUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khởi tạo &amp; Phê duyệt.
        /// </summary>
        public static string InitiateAndApprove {
            get {
                return ResourceManager.GetString("InitiateAndApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID không hợp lệ.
        /// </summary>
        public static string InvalidRequestID {
            get {
                return ResourceManager.GetString("InvalidRequestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KTLM Comment.
        /// </summary>
        public static string KTLMComment {
            get {
                return ResourceManager.GetString("KTLMComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KTTB Comment.
        /// </summary>
        public static string KTTBComment {
            get {
                return ResourceManager.GetString("KTTBComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bước cuối.
        /// </summary>
        public static string LastStep {
            get {
                return ResourceManager.GetString("LastStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý, theo dõi và phê duyệt các request test run một cách nhanh chóng, thuận tiện..
        /// </summary>
        public static string ManageTestRunRequests {
            get {
                return ResourceManager.GetString("ManageTestRunRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý, theo dõi và phê duyệt các request test run một cách nhanh chóng, thuận tiện..
        /// </summary>
        public static string ManageTrackApprove {
            get {
                return ResourceManager.GetString("ManageTrackApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tối đa: 10MB mỗi file.
        /// </summary>
        public static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CẦN CHỈNH SỬA.
        /// </summary>
        public static string NeedEdit {
            get {
                return ResourceManager.GetString("NeedEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cần được chỉnh sửa theo yêu cầu từ chối.
        /// </summary>
        public static string NeedsEditAccordingToRejection {
            get {
                return ResourceManager.GetString("NeedsEditAccordingToRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có đơn test run mới cần xử lý.
        /// </summary>
        public static string NewTestRunRequest {
            get {
                return ResourceManager.GetString("NewTestRunRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung NG.
        /// </summary>
        public static string NGContent {
            get {
                return ResourceManager.GetString("NGContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin NG (nếu có).
        /// </summary>
        public static string NGInfo {
            get {
                return ResourceManager.GetString("NGInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG số: r =.
        /// </summary>
        public static string NGNumber {
            get {
                return ResourceManager.GetString("NGNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có request nào đã hoàn thành..
        /// </summary>
        public static string NoCompletedRequests {
            get {
                return ResourceManager.GetString("NoCompletedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có tài liệu nào được đính kèm.
        /// </summary>
        public static string NoDocuments {
            get {
                return ResourceManager.GetString("NoDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có lý do.
        /// </summary>
        public static string NoReason {
            get {
                return ResourceManager.GetString("NoReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có request nào bị từ chối.
        /// </summary>
        public static string NoRejectedRequests {
            get {
                return ResourceManager.GetString("NoRejectedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện tại chưa có request nào trong giai đoạn.
        /// </summary>
        public static string NoRequestsInPhase {
            get {
                return ResourceManager.GetString("NoRequestsInPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có request nào.
        /// </summary>
        public static string NoRequestsYet {
            get {
                return ResourceManager.GetString("NoRequestsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ý: Bạn có thể chỉnh sửa lại các request bị từ chối nếu bạn là người tạo..
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú:.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú/Chỉnh sửa.
        /// </summary>
        public static string NotesEdits {
            get {
                return ResourceManager.GetString("NotesEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có user nào trong hệ thống.
        /// </summary>
        public static string NoUsersInSystem {
            get {
                return ResourceManager.GetString("NoUsersInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK số: n =.
        /// </summary>
        public static string OKNumber {
            get {
                return ResourceManager.GetString("OKNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff PCB điền form.
        /// </summary>
        public static string PCBStaffDataEntry {
            get {
                return ResourceManager.GetString("PCBStaffDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập ghi chú mô tả công việc đã thực hiện!.
        /// </summary>
        public static string PleaseEnterWorkNotes {
            get {
                return ResourceManager.GetString("PleaseEnterWorkNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đăng nhập lại.
        /// </summary>
        public static string PleaseLoginAgain {
            get {
                return ResourceManager.GetString("PleaseLoginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại thông tin đơn và chỉnh sửa theo yêu cầu, sau đó gửi lại để tiếp tục quy trình..
        /// </summary>
        public static string PleaseReviewAndEdit {
            get {
                return ResourceManager.GetString("PleaseReviewAndEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xem lại và chỉnh sửa đơn theo yêu cầu, sau đó gửi lại để tiếp tục quy trình phê duyệt..
        /// </summary>
        public static string PleaseReviewEditAndResubmit {
            get {
                return ResourceManager.GetString("PleaseReviewEditAndResubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn file để upload.
        /// </summary>
        public static string PleaseSelectFile {
            get {
                return ResourceManager.GetString("PleaseSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview tự động cập nhật khi bạn thay đổi thông tin.
        /// </summary>
        public static string PreviewAutoUpdate {
            get {
                return ResourceManager.GetString("PreviewAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh preview sẽ tự động cập nhật khi bạn nhập liệu.
        /// </summary>
        public static string PreviewWillUpdate {
            get {
                return ResourceManager.GetString("PreviewWillUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xử lý đơn trong thời gian sớm nhất để đảm bảo tiến độ test run..
        /// </summary>
        public static string ProcessingNote {
            get {
                return ResourceManager.GetString("ProcessingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo xử lý.
        /// </summary>
        public static string ProcessingNotification {
            get {
                return ResourceManager.GetString("ProcessingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý đơn.
        /// </summary>
        public static string ProcessRequest {
            get {
                return ResourceManager.GetString("ProcessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Lượng.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do/Ghi chú.
        /// </summary>
        public static string ReasonNotes {
            get {
                return ResourceManager.GetString("ReasonNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nhận hàng test run.
        /// </summary>
        public static string ReceivedTestRunGoods {
            get {
                return ResourceManager.GetString("ReceivedTestRunGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm mới.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tài khoản.
        /// </summary>
        public static string RegisterAccount {
            get {
                return ResourceManager.GetString("RegisterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tại đây.
        /// </summary>
        public static string RegisterHere {
            get {
                return ResourceManager.GetString("RegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối phê duyệt.
        /// </summary>
        public static string RejectApproval {
            get {
                return ResourceManager.GetString("RejectApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị từ chối.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối lúc: {0}.
        /// </summary>
        public static string RejectedAt {
            get {
                return ResourceManager.GetString("RejectedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người từ chối.
        /// </summary>
        public static string RejectedBy {
            get {
                return ResourceManager.GetString("RejectedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request NG.
        /// </summary>
        public static string RejectedRequests {
            get {
                return ResourceManager.GetString("RejectedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request bị từ chối (NG).
        /// </summary>
        public static string RejectedRequestsTitle {
            get {
                return ResourceManager.GetString("RejectedRequestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bước bị từ chối.
        /// </summary>
        public static string RejectedStep {
            get {
                return ResourceManager.GetString("RejectedStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị từ chối.
        /// </summary>
        public static string RejectionRate {
            get {
                return ResourceManager.GetString("RejectionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian từ chối.
        /// </summary>
        public static string RejectionTime {
            get {
                return ResourceManager.GetString("RejectionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo từ chối.
        /// </summary>
        public static string RejectNotification {
            get {
                return ResourceManager.GetString("RejectNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do từ chối.
        /// </summary>
        public static string RejectReason {
            get {
                return ResourceManager.GetString("RejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do từ chối là tùy chọn. Nếu có nhập sẽ được gửi email thông báo..
        /// </summary>
        public static string RejectReasonOptional {
            get {
                return ResourceManager.GetString("RejectReasonOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối sẽ gửi đơn về cho người có thể chỉnh sửa..
        /// </summary>
        public static string RejectWarning {
            get {
                return ResourceManager.GetString("RejectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Phát Hành.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn.
        /// </summary>
        public static string RequestCode {
            get {
                return ResourceManager.GetString("RequestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin Request.
        /// </summary>
        public static string RequestInformation {
            get {
                return ResourceManager.GetString("RequestInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách Request.
        /// </summary>
        public static string RequestList {
            get {
                return ResourceManager.GetString("RequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách Request theo Giai đoạn.
        /// </summary>
        public static string RequestListByPhase {
            get {
                return ResourceManager.GetString("RequestListByPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy request.
        /// </summary>
        public static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy request {0}.
        /// </summary>
        public static string RequestNotFoundWithID {
            get {
                return ResourceManager.GetString("RequestNotFoundWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request trong giai đoạn.
        /// </summary>
        public static string RequestsInPhase {
            get {
                return ResourceManager.GetString("RequestsInPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hành động cần thực hiện.
        /// </summary>
        public static string RequiredAction {
            get {
                return ResourceManager.GetString("RequiredAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GỬI LẠI.
        /// </summary>
        public static string Resubmitted {
            get {
                return ResourceManager.GetString("Resubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con dấu.
        /// </summary>
        public static string Seal {
            get {
                return ResourceManager.GetString("Seal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con dấu của.
        /// </summary>
        public static string SealOf {
            get {
                return ResourceManager.GetString("SealOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm theo tên, ADID, phòng ban....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Chọn phòng ban --.
        /// </summary>
        public static string SelectDepartment {
            get {
                return ResourceManager.GetString("SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đã chọn:.
        /// </summary>
        public static string SelectedFiles {
            get {
                return ResourceManager.GetString("SelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn file.
        /// </summary>
        public static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Chọn chức vụ --.
        /// </summary>
        public static string SelectPosition {
            get {
                return ResourceManager.GetString("SelectPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi server: {0}.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string ShowingResults {
            get {
                return ResourceManager.GetString("ShowingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff EE điền form.
        /// </summary>
        public static string StaffEEForm {
            get {
                return ResourceManager.GetString("StaffEEForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng dấu kèm phê duyệt.
        /// </summary>
        public static string StampWithApproval {
            get {
                return ResourceManager.GetString("StampWithApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê: {0} users.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà Cung Cấp.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ: PDF, Word, Excel, Hình ảnh, Text, ZIP, RAR.
        /// </summary>
        public static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng hệ thống.
        /// </summary>
        public static string SystemStatus {
            get {
                return ResourceManager.GetString("SystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn Test Run.
        /// </summary>
        public static string TestRunRequest {
            get {
                return ResourceManager.GetString("TestRunRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn Test Run cần phê duyệt.
        /// </summary>
        public static string TestRunRequestApproval {
            get {
                return ResourceManager.GetString("TestRunRequestApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn Test Run cần xử lý.
        /// </summary>
        public static string TestRunRequestProcessing {
            get {
                return ResourceManager.GetString("TestRunRequestProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả Test Run.
        /// </summary>
        public static string TestRunResults {
            get {
                return ResourceManager.GetString("TestRunResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống test run nội bộ EPE-PCB.
        /// </summary>
        public static string TestRunSystemTitle {
            get {
                return ResourceManager.GetString("TestRunSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm nay.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng: {0} request bị từ chối.
        /// </summary>
        public static string TotalRejected {
            get {
                return ResourceManager.GetString("TotalRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng Request.
        /// </summary>
        public static string TotalRequests {
            get {
                return ResourceManager.GetString("TotalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xác định.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xác định.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload tài liệu.
        /// </summary>
        public static string UploadDocument {
            get {
                return ResourceManager.GetString("UploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi upload tài liệu. Vui lòng thử lại.
        /// </summary>
        public static string UploadDocumentError {
            get {
                return ResourceManager.GetString("UploadDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload tài liệu thành công!.
        /// </summary>
        public static string UploadDocumentSuccess {
            get {
                return ResourceManager.GetString("UploadDocumentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian upload.
        /// </summary>
        public static string UploadedAt {
            get {
                return ResourceManager.GetString("UploadedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người upload.
        /// </summary>
        public static string UploadedBy {
            get {
                return ResourceManager.GetString("UploadedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách Users.
        /// </summary>
        public static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem và phê duyệt đơn.
        /// </summary>
        public static string ViewAndApproveRequest {
            get {
                return ResourceManager.GetString("ViewAndApproveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem và xử lý đơn.
        /// </summary>
        public static string ViewAndProcess {
            get {
                return ResourceManager.GetString("ViewAndProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tài liệu.
        /// </summary>
        public static string ViewDocuments {
            get {
                return ResourceManager.GetString("ViewDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thông tin.
        /// </summary>
        public static string ViewInformation {
            get {
                return ResourceManager.GetString("ViewInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ý.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã bị từ chối bởi.
        /// </summary>
        public static string WasRejectedBy {
            get {
                return ResourceManager.GetString("WasRejectedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng đến với hệ thống Test Run!.
        /// </summary>
        public static string WelcomeToTestRun {
            get {
                return ResourceManager.GetString("WelcomeToTestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng đến với hệ thống Test Run!.
        /// </summary>
        public static string WelcomeToTestRunSystem {
            get {
                return ResourceManager.GetString("WelcomeToTestRunSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú công việc đã thực hiện:.
        /// </summary>
        public static string WorkCompletedNotes {
            get {
                return ResourceManager.GetString("WorkCompletedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn được chỉ định phê duyệt đơn test run.
        /// </summary>
        public static string YouAreDesignatedToApprove {
            get {
                return ResourceManager.GetString("YouAreDesignatedToApprove", resourceCulture);
            }
        }
    }
}
